<%@ Page Title="" Language="C#" MasterPageFile="~/View/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageRamen.aspx.cs" Inherits="RAAMEN_PSD_FINAL_PROJECT.View.Admin.ManageRamen" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Manage Ramen</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="margin-top: 55px;padding: 20px">
        <asp:Label ID="Label1" runat="server" Text="Customers"></asp:Label>
        <br />
        <asp:GridView ID="customerGridView" runat="server"></asp:GridView>
        <br />
        <asp:Label ID="Label2" runat="server" Text="Ramens"></asp:Label>
        <br />
        <asp:GridView ID="ramenGridView" runat="server" OnRowDeleting="ramenGridView_RowDeleting" AutoGenerateDeleteButton="true" OnRowEditing="ramenGridView_RowEditing" AutoGenerateEditButton="true"></asp:GridView>
        <br />
        <asp:Button ID="insert_ramen_btn" runat="server" Text="Insert Ramen" OnClick="insert_ramen_btn_Click" />
    </div>
</asp:Content>
